### ISSUE TITLE
Writersguide: error on install instructions

### ISSUE THREAD

**Issue by TheDutchCoder** [webpack/webpack.js.org#1406]
Following the instructions in the [`writer's guide`](https://webpack.js.org/writers-guide/#running-the-site) results in an error when running `npm start` after `npm install`.

Reading through the errors I see that `scripts/fetch_package_files.js` errors out on the `let` declaration without using `strict mode`.

Changing that makes this part work, but then it fails on `antwar.config.js:230` where a default assignment is used:

``` bash
function section(title, contentCb, redirects = {}) {
                                             ^

SyntaxError: Unexpected token =
```

Any help would be appreciated!

Here's the generated log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/node',
1 verbose cli   '/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.0.0
3 info using node@v4.8.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle webpack.js.org@0.1.2~prestart: webpack.js.org@0.1.2
6 silly lifecycle webpack.js.org@0.1.2~prestart: no script for prestart, continuing
7 info lifecycle webpack.js.org@0.1.2~start: webpack.js.org@0.1.2
8 verbose lifecycle webpack.js.org@0.1.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle webpack.js.org@0.1.2~start: PATH: /Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/bin/node-gyp-bin:/Users/reinierkaper/projects/webpack.js.org/node_modules/.bin:/Users/reinierkaper/.rvm/gems/ruby-2.0.0-p648/bin:/Users/reinierkaper/.rvm/gems/ruby-2.0.0-p648@global/bin:/Users/reinierkaper/.rvm/rubies/ruby-2.0.0-p648/bin:/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/reinierkaper/.rvm/gems/ruby-2.0.0-p648/bin:/Users/reinierkaper/.rvm/gems/ruby-2.0.0-p648@global/bin:/Users/reinierkaper/.rvm/rubies/ruby-2.0.0-p648/bin:/Users/reinierkaper/.rvm/bin:/Users/reinierkaper/.rvm/bin
10 verbose lifecycle webpack.js.org@0.1.2~start: CWD: /Users/reinierkaper/projects/webpack.js.org
11 silly lifecycle webpack.js.org@0.1.2~start: Args: [ '-c',
11 silly lifecycle   'npm run init:generated && npm run fetch && node ./bootstrap.js' ]
12 silly lifecycle webpack.js.org@0.1.2~start: Returned: code: 1  signal: null
13 info lifecycle webpack.js.org@0.1.2~start: Failed to exec start script
14 verbose stack Error: webpack.js.org@0.1.2 start: `npm run init:generated && npm run fetch && node ./bootstrap.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:862:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
15 verbose pkgid webpack.js.org@0.1.2
16 verbose cwd /Users/reinierkaper/projects/webpack.js.org
17 verbose Darwin 16.6.0
18 verbose argv "/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/node" "/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/npm" "start"
19 verbose node v4.8.2
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 1
23 error webpack.js.org@0.1.2 start: `npm run init:generated && npm run fetch && node ./bootstrap.js`
23 error Exit status 1
24 error Failed at the webpack.js.org@0.1.2 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by skipjack** [comment]
Hmmm I think you may need a newer version of Node.

**Comment by skipjack** [comment]
I think 6 and ^ is where they started introducing those ES6 features.

cc @bebraw

**Comment by TheDutchCoder** [comment]
Ah that would make sense.

I'll give that a shot and see if it works. If so I'll open a PR to add it into the instructions ;)

**Comment by TheDutchCoder** [comment]
Yes that did the trick, thanks!

Will probably open a PR to add to the docs as well ;)

**Comment by skipjack** [comment]
Yeah that's a good idea.
