### ISSUE TITLE
Use of BannerPlugin.js results in error: str.indexOf is not a function

### ISSUE THREAD

**Issue by WouterVanherck** [webpack/webpack.js.org#1900]
I'm using BannerPlugin in `webpack.config.prod.js` / `webpack.config.dev.js`:

```
module.exports = {
  ...
  plugins: [
    ...
    new webpack.BannerPlugin({
      banner: "#!/usr/bin/env node",
      raw: true
    })
  ],
  ...
};
```

Which results in the error: `str.indexOf is not a function`

```
...\node_modules\webpack\lib\BannerPlugin.js:9
        if(str.indexOf("\n") < 0) return "/*! " + str + " */";
               ^

TypeError: str.indexOf is not a function
    at wrapComment (...\node_modules\webpack\lib\BannerPlugin.js:9:9)
    at new BannerPlugin (...\node_modules\webpack\lib\BannerPlugin.js:15:44)
    at Object.<anonymous> (...\config\webpack.config.prod.js:261:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...\scripts\build.js:17:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

How does one resolve this without having to modify BannerPlugin.js?  
[Asked on StackOverflow](https://stackoverflow.com/questions/49189804/react-use-of-bannerplugin-js-results-in-error-str-indexof-is-not-a-function)

**Comment by montogeek** [comment]
This is not an issue with webpack website documentation.
Please submit it to BannerPlugin repository.
