### ISSUE TITLE
`antwar.config.js` contains Chinese and causes the build to fail

### ISSUE THREAD

**Issue by dear-lizhihua** [webpack/webpack.js.org#2170]
In this [`pull-request`](https://github.com/docschina/webpack.js.org/pull/494), [docschina/webpack.js.org CI](https://travis-ci.org/docschina/webpack.js.org/builds/378299960) reported an error:
```
/home/travis/build/docschina/webpack.js.org/build/site.js:28
 */,n.exports=function(n,a){if(!t.canUseDOM||a&&!("addEventListener"in document))return!1;var e="on"+n,o=e in document;if(!o){var c=document.createElement("div");c.setAttribute(e,"return;"),o="function"==typeof c[e]}return!o&&s&&"wheel"===n&&(o=document.implementation.hasFeature("Events.wheel","3.0")),o}},function(n,a,e){"use strict";n.exports=function(n){var a=n.target||n.srcElement||window;return a.correspondingUseElement&&(a=a.correspondingUseElement),3===a.nodeType?a.parentNode:a}},function(n,a,e){"use strict";var s=null;function t(n,a,e){try{a(e)}catch(n){null===s&&(s=n)}}var o={invokeGuardedCallback:t,invokeGuardedCallbackWithCatch:t,rethrowCaughtError:function(){if(s){var n=s;throw s=null,n}}};n.exports=o},function(n,a,e){"use strict";var s,t,o=e(4),c=e(72);e(2),e(5);function p(n,a,e,s){var t=n.type||"unknown-event";n.currentTarget=l.getNodeFromInstance(s),a?c.invokeGuardedCallbackWithCatch(t,e,n):c.invokeGuardedCallback(t,e,n),n.currentTar
Error: Cannot find module ".///index.md".
    at o (/home/travis/build/docschina/webpack.js.org/build/site.js:28:2797178)
    at t (/home/travis/build/docschina/webpack.js.org/build/site.js:28:2797119)
    at a.default (/home/travis/build/docschina/webpack.js.org/build/site.js:6:8005)
    at l._constructComponentWithoutOwner (/home/travis/build/docschina/webpack.js.org/build/site.js:28:214041)
    at l._constructComponent (/home/travis/build/docschina/webpack.js.org/build/site.js:28:213895)
    at l.mountComponent (/home/travis/build/docschina/webpack.js.org/build/site.js:28:213050)
    at Object.mountComponent (/home/travis/build/docschina/webpack.js.org/build/site.js:14:76394)
    at Y.mountChildren (/home/travis/build/docschina/webpack.js.org/build/site.js:28:220959)
    at Y._createContentMarkup (/home/travis/build/docschina/webpack.js.org/build/site.js:28:236521)
    at Y.mountComponent (/home/travis/build/docschina/webpack.js.org/build/site.js:28:235189)
/home/travis/build/docschina/webpack.js.org/build/site.js:28
 */,n.exports=function(n,a){if(!t.canUseDOM||a&&!("addEventListener"in document))return!1;var e="on"+n,o=e in document;if(!o){var c=document.createElement("div");c.setAttribute(e,"return;"),o="function"==typeof c[e]}return!o&&s&&"wheel"===n&&(o=document.implementation.hasFeature("Events.wheel","3.0")),o}},function(n,a,e){"use strict";n.exports=function(n){var a=n.target||n.srcElement||window;return a.correspondingUseElement&&(a=a.correspondingUseElement),3===a.nodeType?a.parentNode:a}},function(n,a,e){"use strict";var s=null;function t(n,a,e){try{a(e)}catch(n){null===s&&(s=n)}}var o={invokeGuardedCallback:t,invokeGuardedCallbackWithCatch:t,rethrowCaughtError:function(){if(s){var n=s;throw s=null,n}}};n.exports=o},function(n,a,e){"use strict";var s,t,o=e(4),c=e(72);e(2),e(5);function p(n,a,e,s){var t=n.type||"unknown-event";n.currentTarget=l.getNodeFromInstance(s),a?c.invokeGuardedCallbackWithCatch(t,e,n):c.invokeGuardedCallback(t,e,n),n.currentTar
```

After troubleshooting, it was found to be [`antwar.config.js`](https://github.com/docschina/webpack.js.org/pull/494/commits/916a942104a818df79bb75c09f3968c372acb4a0#diff-454cc7d35544d042a685f267fef1f668)

**Comment by dear-lizhihua** [comment]
You can paste this code into `antwar.config.js` directly under the master branch of the [webpack/webpack.js.org] repository to reproduce the problem.
```
const path = require('path');
const combineContexts = require('./src/utilities/combine-contexts');

module.exports = () => ({
  maximumWorkers: process.env.TRAVIS && 1,
  template: {
    file: path.join(__dirname, 'template.ejs')
  },
  output: 'build',
  title: 'webpack 中文文档',
  keywords: ['webpack', 'javascript', 'web development', 'programming'],
  layout: () => require('./src/components/Site/Site.jsx').default,
  paths: {
    '/': {
      title: '首页',
      layout: () => require('./src/components/Page/Page.jsx').default,
      content: () => require.context('./loaders/page-loader!./src/content', false, /^\.\/.*\.md$/),
      index: () => require('./src/components/Splash/Splash.jsx').default
    },
    concepts: {
      title: '概念',
      url: ({ sectionName, fileName }) => `/${sectionName}/${fileName}/`,
      layout: () => require('./src/components/Page/Page.jsx').default,
      content: () => require.context('./loaders/page-loader!./src/content/concepts', false, /^\.\/.*\.md$/)
    },
    configuration: {
      title: '配置',
      url: ({ sectionName, fileName }) => `/${sectionName}/${fileName}/`,
      layout: () => require('./src/components/Page/Page.jsx').default,
      content: () => require.context('./loaders/page-loader!./src/content/configuration', false, /^\.\/.*\.md$/)
    },
    api: {
      title: 'API',
      url: ({ sectionName, fileName }) => `/${sectionName}/${fileName}/`,
      layout: () => require('./src/components/Page/Page.jsx').default,
      content: () => require.context('./loaders/page-loader!./src/content/api', false, /^\.\/.*\.md$/)
    },
    guides: {
      title: '指南',
      url: ({ sectionName, fileName }) => `/${sectionName}/${fileName}/`,
      layout: () => require('./src/components/Page/Page.jsx').default,
      content: () => require.context('./loaders/page-loader!./src/content/guides', false, /^\.\/.*\.md$/)
    },
    plugins: {
      title: '插件',
      url: ({ sectionName, fileName }) => `/${sectionName}/${fileName}/`,
      layout: () => require('./src/components/Page/Page.jsx').default,
      content: () => {
        return combineContexts(
          require.context('./loaders/page-loader!./src/content/plugins', false, /^\.\/.*\.md$/),
          require.context('./loaders/page-loader!./generated/plugins', false, /^\.\/.*\.md$/)
        );
      }
    },
    loaders: {
      title: 'loaders',
      url: ({ sectionName, fileName }) => `/${sectionName}/${fileName}/`,
      layout: () => require('./src/components/Page/Page.jsx').default,
      content: () => {
        return combineContexts(
          require.context('./loaders/page-loader!./src/content/loaders', false, /^\.\/.*\.md$/),
          require.context('./loaders/page-loader!./generated/loaders', false, /^\.\/.*\.md$/)
        );
      }
    },
    contribute: {
      title: '贡献',
      url: ({ sectionName, fileName }) => `/${sectionName}/${fileName}/`,
      layout: () => require('./src/components/Page/Page.jsx').default,
      content: () => require.context('./loaders/page-loader!./src/content/contribute', false, /^\.\/.*\.md$/)
    },
    migrate: {
      title: '迁移',
      url: ({ sectionName, fileName }) => `/${sectionName}/${fileName}/`,
      layout: () => require('./src/components/Page/Page.jsx').default,
      content: () => require.context('./loaders/page-loader!./src/content/migrate', false, /^\.\/.*\.md$/)
    },
    vote: () => require('./src/components/Vote/Vote.jsx').default,
    organization: () => require('./src/components/Organization/Organization.jsx').default,
    'starter-kits': () => require('./src/components/StarterKits/StarterKits.jsx').default
  }
});
```

**Comment by montogeek** [comment]
cc @bebraw

**Comment by dear-lizhihua** [comment]
Hello, @bebraw
How is this problem? If it is not fixed, chinese documents can only display english navigation.

**Comment by montogeek** [comment]
This is not longer used.
