### ISSUE TITLE
Infra: Build Failing (master)

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack.js.org#2878]
Build on master failing.

```
 git pull      
Already up to date.
 ⚙ wasd@turing-machine  ~/webpack/webpack.js.org   master 
 npm run build

> webpack.js.org@0.1.2 prebuild /home/wasd/webpack/webpack.js.org
> npm run clean


> webpack.js.org@0.1.2 clean /home/wasd/webpack/webpack.js.org
> rimraf ./dist src/content/**/_*.md src/**/_*.json


> webpack.js.org@0.1.2 build /home/wasd/webpack/webpack.js.org
> run-s fetch content && cross-env NODE_ENV=production webpack --config webpack.prod.js


> webpack.js.org@0.1.2 fetch /home/wasd/webpack/webpack.js.org
> run-p fetch:*


> webpack.js.org@0.1.2 fetch:supporters /home/wasd/webpack/webpack.js.org
> node src/utilities/fetch-supporters.js


> webpack.js.org@0.1.2 fetch:starter-kits /home/wasd/webpack/webpack.js.org
> node src/utilities/fetch-starter-kits.js


> webpack.js.org@0.1.2 fetch:readmes /home/wasd/webpack/webpack.js.org
> node src/utilities/fetch-package-readmes.js

Fetched 1 file: _starter-kits.json
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/raw-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/raw-loader/blob/master/LICENSE
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/val-loader/blob/master/LICENSE
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/url-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/url-loader/blob/master/LICENSE
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/worker-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/worker-loader/blob/master/LICENSE
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/exports-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/exports-loader/blob/master/LICENSE
REWRITE URL: https://webpack.js.org/configuration/module/#rule-options-rule-query --> /configuration/module/#rule-options-rule-query
REWRITE URL: https://webpack.js.org/configuration/resolve/ --> /configuration/resolve/
REWRITE URL: https://webpack.js.org/configuration/resolve/#resolve-modules --> /configuration/resolve/#resolve-modules
REWRITE URL: https://webpack.js.org/concepts/hot-module-replacement/ --> /concepts/hot-module-replacement/
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/less-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/less-loader/blob/master/LICENSE
REWRITE URL: https://webpack.js.org/migrate/3/#json-loader-is-not-required-anymore --> /migrate/3/#json-loader-is-not-required-anymore
REWRITE URL: https://webpack.js.org/configuration/output/#output-chunkfilename --> /configuration/output/#output-chunkfilename
REWRITE URL: https://webpack.js.org/api/loaders/#the-loader-context --> /api/loaders/#the-loader-context
REWRITE URL: http://www.JSHint.com/docs/reporters/ --> http://www.jshint.com/docs/reporters/
REWRITE URL: ./.github/CONTRIBUTING --> https://github.com/webpack-contrib/jshint-loader/blob/master/.github/CONTRIBUTING
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/jshint-loader/blob/master/LICENSE
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/expose-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/expose-loader/blob/master/LICENSE
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/transform-loader/blob/master/LICENSE
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/yaml-frontmatter-loader/blob/master/LICENSE
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/multi-loader/blob/master/LICENSE
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/node-loader/blob/master/LICENSE
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/react-proxy-loader/blob/master/LICENSE
REWRITE URL: https://webpack.js.org/concepts/#loaders --> /concepts/#loaders
REWRITE URL: https://webpack.js.org/configuration/devtool/ --> /configuration/devtool/
REWRITE URL: https://webpack.js.org/configuration/ --> /configuration/
REWRITE URL: https://webpack.js.org/configuration/module/#rule-include --> /configuration/module/#rule-include
REWRITE URL: https://webpack.js.org/configuration/module/#rule-exclude --> /configuration/module/#rule-exclude
REWRITE URL: https://webpack.js.org/configuration/devtool/ --> /configuration/devtool/
Generated: src/content/loaders/_raw-loader.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/LICENSE
REWRITE URL: https://webpack.js.org/loaders/ --> /loaders/
REWRITE URL: https://webpack.js.org/concepts/hot-module-replacement --> /concepts/hot-module-replacement
REWRITE URL: https://webpack.js.org/configuration/output/#output-publicpath --> /configuration/output/#output-publicpath
REWRITE URL: https://webpack.js.org/api/loaders/#the-loader-context --> /api/loaders/#the-loader-context
REWRITE URL: https://peerigon.com --> https://peerigon.com/
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/LICENSE
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/stylelint-webpack-plugin/blob/master/LICENSE
Generated: src/content/loaders/_val-loader.md
Generated: src/content/loaders/_url-loader.md
Generated: src/content/loaders/_i18n-loader.md
Generated: src/content/loaders/_json5-loader.md
Generated: src/content/loaders/_worker-loader.md
Generated: src/content/loaders/_exports-loader.md
Generated: src/content/loaders/_script-loader.md
Generated: src/content/loaders/_less-loader.md
Generated: src/content/loaders/_json-loader.md
Generated: src/content/loaders/_bundle-loader.md
REWRITE URL: https://webpack.js.org/plugins/split-chunks-plugin/ --> /plugins/split-chunks-plugin/
REWRITE URL: https://webpack.js.org/configuration/optimization/#optimization-concatenatemodules --> /configuration/optimization/#optimization-concatenatemodules
REWRITE URL: https://webpack.js.org/api/module-variables/#__webpack_public_path__-webpack-specific- --> /api/module-variables/#__webpack_public_path__-webpack-specific-
REWRITE URL: https://webpack.js.org/configuration/entry-context/#context --> /configuration/entry-context/#context
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/file-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/file-loader/blob/master/LICENSE
REWRITE URL: https://webpack.js.org/concepts/module-resolution/ --> /concepts/module-resolution/
REWRITE URL: https://webpack.js.org/concepts/hot-module-replacement/ --> /concepts/hot-module-replacement/
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/LICENSE
Generated: src/content/loaders/_jshint-loader.md
Generated: src/content/loaders/_expose-loader.md
Generated: src/content/loaders/_transform-loader.md
Generated: src/content/loaders/_coverjs-loader.md
Generated: src/content/loaders/_html-loader.md
Generated: src/content/loaders/_istanbul-instrumenter-loader.md
Generated: src/content/loaders/_mocha-loader.md
Generated: src/content/loaders/_coffee-redux-loader.md
Generated: src/content/loaders/_yaml-frontmatter-loader.md
Generated: src/content/loaders/_multi-loader.md
Generated: src/content/loaders/_node-loader.md
Generated: src/content/loaders/_react-proxy-loader.md
Generated: src/content/loaders/_source-map-loader.md
Generated: src/content/loaders/_svg-inline-loader.md
Generated: src/content/plugins/_extract-text-webpack-plugin.md
Generated: src/content/plugins/_babel-minify-webpack-plugin.md
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/LICENSE
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/LICENSE
Generated: src/content/plugins/_zopfli-webpack-plugin.md
Generated: src/content/plugins/_mini-css-extract-plugin.md
Generated: src/content/loaders/_thread-loader.md
Generated: src/content/loaders/_gzip-loader.md
Generated: src/content/loaders/_restyle-loader.md
Generated: src/content/loaders/_extract-loader.md
Generated: src/content/plugins/_compression-webpack-plugin.md
Generated: src/content/plugins/_component-webpack-plugin.md
Generated: src/content/plugins/_stylelint-webpack-plugin.md
Generated: src/content/plugins/_closure-webpack-plugin.md
Generated: src/content/loaders/_sass-loader.md
Generated: src/content/loaders/_file-loader.md
Generated: src/content/plugins/_copy-webpack-plugin.md
Generated: src/content/plugins/_terser-webpack-plugin.md
Generated: src/content/plugins/_uglifyjs-webpack-plugin.md
Generated: src/content/loaders/_coffee-loader.md
REWRITE URL: ./.github/CONTRIBUTING --> https://github.com/webpack-contrib/null-loader/blob/master/.github/CONTRIBUTING
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/null-loader/blob/master/LICENSE
Generated: src/content/loaders/_imports-loader.md
Generated: src/content/loaders/_null-loader.md
REWRITE URL: https://webpack.js.org/ --> /
REWRITE URL: https://webpack.js.org/configuration/module/#rule-use --> /configuration/module/#rule-use
REWRITE URL: https://webpack.js.org/guides/shimming/ --> /guides/shimming/
REWRITE URL: https://webpack.js.org/guides/shimming/#exports-loader --> /guides/shimming/#exports-loader
REWRITE URL: https://webpack.js.org/guides/shimming/#imports-loader --> /guides/shimming/#imports-loader
REWRITE URL: https://webpack.js.org/guides/shimming/#provideplugin --> /guides/shimming/#provideplugin
REWRITE URL: https://webpack.js.org/plugins/normal-module-replacement-plugin/ --> /plugins/normal-module-replacement-plugin/
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/cache-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/cache-loader/blob/master/LICENSE
REWRITE URL: ./docs/EXTENDS.md --> https://github.com/webpack-contrib/config-loader/blob/master/docs/EXTENDS.md
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/config-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/config-loader/blob/master/LICENSE
REWRITE URL: https://webpack.js.org/loaders/ --> /loaders/
REWRITE URL: https://webpack.js.org/configuration/module/#rule-options-rule-query --> /configuration/module/#rule-options-rule-query
Generated: src/content/loaders/_polymer-webpack-loader.md
Generated: src/content/loaders/_postcss-loader.md
Generated: src/content/loaders/_style-loader.md
Generated: src/content/plugins/_i18n-webpack-plugin.md
Generated: src/content/loaders/_cache-loader.md
Generated: src/content/plugins/_npm-install-webpack-plugin.md
Generated: src/content/loaders/_config-loader.md
Generated: src/content/loaders/_babel-loader.md
REWRITE URL: ./.github/CONTRIBUTING.md --> https://github.com/webpack-contrib/css-loader/blob/master/.github/CONTRIBUTING.md
REWRITE URL: ./LICENSE --> https://github.com/webpack-contrib/css-loader/blob/master/LICENSE
REWRITE URL: https://webpack.js.org/configuration/module/#useentry --> /configuration/module/#useentry
REWRITE URL: CHANGELOG.md --> https://github.com/webpack-contrib/eslint-loader/blob/master/CHANGELOG.md
REWRITE URL: LICENSE --> https://github.com/webpack-contrib/eslint-loader/blob/master/LICENSE
Generated: src/content/loaders/_css-loader.md
Generated: src/content/loaders/_eslint-loader.md
Fetched 1 file: _supporters.json

> webpack.js.org@0.1.2 content /home/wasd/webpack/webpack.js.org
> node src/scripts/build-content-tree.js ./src/content ./src/_content.json

/home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/bin/cli.js:231
				throw err;
				^

Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
    at Object.get [as CommonsChunkPlugin] (/home/wasd/webpack/webpack.js.org/node_modules/webpack/lib/webpack.js:185:10)
    at module.exports.env (/home/wasd/webpack/webpack.js.org/webpack.prod.js:107:28)
    at handleFunction (/home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/bin/prepareOptions.js:21:13)
    at prepareOptions (/home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/bin/prepareOptions.js:9:5)
    at requireConfig (/home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/bin/convert-argv.js:118:14)
    at /home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at yargs.parse (/home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/bin/cli.js:228:39)
    at Object.parse (/home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/bin/cli.js:206:8
    at Object.<anonymous> (/home/wasd/webpack/webpack.js.org/node_modules/webpack-cli/bin/cli.js:505:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/wasd/webpack/webpack.js.org/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack.js.org@0.1.2 build: `run-s fetch content && cross-env NODE_ENV=production webpack --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack.js.org@0.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by EugeneHlushko** [comment]
Please provide OS and node versions. Please try using `yarn` v > 1.1 as we do have `yarn.lock`

**Comment by pranshuchittora** [comment]
`yarn build` works :tada:
